import { Component, OnInit } from '@angular/core'
import { Router } from '@angular/router'
import { ConfigurationsService, NsPage } from '@sunbird-cb/utils'

@Component({
  selector: 'ws-app-my-dashboard-home',
  templateUrl: './my-dashboard-home.component.html',
  styleUrls: ['./my-dashboard-home.component.scss'],
})
export class MyDashboardHomeComponent implements OnInit {

  constructor(private router: Router, private configSvc: ConfigurationsService) { }
  pageNavbar: Partial<NsPage.INavBackground> = this.configSvc.pageNavBar

  selectedDashboardId = "";

  // List of available dashboards
  dashboardList = [
    {
      statusInfo: {
        statusCode: 200,
        statusMessage: "success",
        errorMessage: "",
      },
      responseData: [
        {
          name: "Overview",
          id: "overview",
        },
        {
          name: "Informatics",
          id: "informatics",
        },
      ],
    },
  ];

  currentDashboard: any = [];

  dashboardOne = {
    showFilters: "true",
    showWidgets: "true",
    filtersDetails: [
      {
        name: "Content",
        id: 1,
        key: "content",
        values: [
          "All",
          "MDO's"
        ],
      },
    ],
    visualizationDetails: [
      {
        row: 1,
        name: "Visualization Row 1",
        vizArray: [
          {
            id: 11,
            name: "Number Of Competencies",
            dimensions: {
              height: 250,
              width: 6,
            },
            vizType: "chart",
            noUnit: true,
            isCollapsible: false,
            charts: [
              {
                id: "numberOfCompetencies",
                name: "Number Of Competencies",
                code: "",
                chartType: "pie",
                filter: "",
                headers: [],
              },
            ],
          },
          {
            id: 12,
            name: "Learning Time Trend",
            dimensions: {
              height: 250,
              width: 6,
            },
            vizType: "chart",
            noUnit: true,
            charts: [
              {
                id: "learningTime",
                name: "Learning Time Trend",
                code: "",
                chartType: "line",
                filter: "",
                headers: [],
              },
            ],
          },
        ],
      },
      {
        row: 2,
        name: "Visualization Row 2",
        vizArray: [
          {
            id: 21,
            name: "Diversity",
            dimensions: {
              height: 250,
              width: 6,
            },
            vizType: "chart",
            noUnit: true,
            isCollapsible: false,
            charts: [
              {
                id: "diversity",
                name: "Diversity",
                code: "",
                chartType: "polararea",
                filter: "",
                headers: [],
              },
            ],
          },
          {
            id: 22,
            name: "Active Learners",
            dimensions: {
              height: 250,
              width: 6,
            },
            vizType: "chart",
            noUnit: true,
            charts: [
              {
                id: "activeLearners",
                name: "Active Learners",
                code: "",
                chartType: "line",
                filter: "",
                headers: [],
              },
            ],
          },
        ],
      },
      {
        row: 3,
        name: "Visualization Row 3",
        vizArray: [
          {
            id: 23,
            name: "CBP onbroading trend",
            dimensions: {
              height: 250,
              width: 6,
            },
            vizType: "chart",
            noUnit: true,
            isCollapsible: false,
            charts: [
              {
                id: "cbpOnBroadingTrend",
                name: "CBP onbroading trend",
                code: "",
                chartType: "bar",
                filter: "",
                headers: [],
              },
            ],
          },
          {
            id: 24,
            name: "Number of positions",
            dimensions: {
              height: 250,
              width: 6,
            },
            vizType: "chart",
            noUnit: true,
            isCollapsible: false,
            charts: [
              {
                id: "numberOfPositions",
                name: "Number of positions",
                code: "",
                chartType: "polararea",
                filter: "",
                headers: [],
              },
            ],
          },
        ],
      },
      {
        row: 3,
        name: "Visualization Row 3",
        vizArray: [
          {
            id: 25,
            name: "Number of competencies by MDO",
            dimensions: {
              height: 250,
              width: 6,
            },
            vizType: "chart",
            noUnit: true,
            isCollapsible: false,
            charts: [
              {
                id: "noOfCompetenciesByMdo",
                name: "Number of competencies by MDO",
                code: "",
                chartType: "horizontal_bar",
                filter: "",
                headers: [],
              },
            ],
          },
        ],
      },
    ],
    chartDetails: [
      {
        statusInfo: {
          statusCode: 200,
          statusMessage: "success",
          errorMessage: "",
        },
        responseData: {
          chartType: "pie",
          visualizationCode: "numberOfCompetencies",
          chartFormat: null,
          drillDownChartId: "none",
          filterKeys: null,
          customData: null,
          dates: null,
          filter: null,
          data: [
            {
              headerName: "Number of Competencies",
              headerValue: 98,
              headerSymbol: "number",
              colorPaletteCode: null,
              colorPaletteId: null,
              plots: [
                {
                  label: "Header",
                  name: "Functional",
                  value: 28.028,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "Behavioural",
                  value: 11.956,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "Domain",
                  value: 58.016,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
              ],
              insight: null,
              isDecimal: null,
            },
          ],
        },
      },
      {
        statusInfo: {
          statusCode: 200,
          statusMessage: "success",
          errorMessage: "",
        },
        responseData: {
          chartType: "line",
          visualizationCode: "learningTime",
          chartFormat: null,
          drillDownChartId: "none",
          filterKeys: null,
          customData: null,
          dates: null,
          filter: null,
          data: [
            {
              headerName: "Learning Time",
              headerValue: 431720.3772538068,
              headerSymbol: "number",
              colorPaletteCode: null,
              colorPaletteId: null,
              plots: [
                {
                  label: "Header",
                  name: "Apr-2020",
                  value: 631.8648329412255,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "May-2020",
                  value: 295.25799994127203,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "Jun-2020",
                  value: 1658.7826694690932,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "Jul-2020",
                  value: 64810.795044640516,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "Aug-2020",
                  value: 94765.17582970156,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "Sep-2020",
                  value: 62954.23232729481,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "Oct-2020",
                  value: 27367.78634477248,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "Nov-2020",
                  value: 67071.49751383436,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "Dec-2020",
                  value: 36885.41300287151,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "Jan-2021",
                  value: 44833.261666659295,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "Feb-2021",
                  value: 30446.310021680656,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
              ],
              insight: null,
              isDecimal: null,
            },
          ],
        },
      },
      {
        statusInfo: {
          statusCode: 200,
          statusMessage: "success",
          errorMessage: "",
        },
        responseData: {
          chartType: "pie",
          visualizationCode: "devicesUsed",
          chartFormat: null,
          drillDownChartId: "none",
          filterKeys: null,
          customData: null,
          dates: null,
          filter: null,
          data: [
            {
              headerName: "Devices Used",
              headerValue: 1411,
              headerSymbol: "number",
              colorPaletteCode: null,
              colorPaletteId: null,
              plots: [
                {
                  label: "Header",
                  name: "Windows",
                  value: 745,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "Android",
                  value: 541,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "Mac OS",
                  value: 74,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "iPhone",
                  value: 48,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "iPad",
                  value: 3,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
              ],
              insight: null,
              isDecimal: null,
            },
          ],
        },
      },
      {
        statusInfo: {
          statusCode: 200,
          statusMessage: "success",
          errorMessage: "",
        },
        responseData: {
          chartType: "polararea",
          visualizationCode: "activeLearners",
          chartFormat: null,
          drillDownChartId: "none",
          filterKeys: null,
          customData: null,
          dates: null,
          filter: null,
          data: [
            {
              headerName: "Active Learners",
              headerValue: 1590,
              headerSymbol: "number",
              colorPaletteCode: null,
              colorPaletteId: null,
              plots: [
                {
                  label: "Header",
                  name: "Apr-2020",
                  value: 30,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "May-2020",
                  value: 31,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "Jun-2020",
                  value: 45,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "Jul-2020",
                  value: 121,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "Aug-2020",
                  value: 265,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "Sep-2020",
                  value: 197,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "Oct-2020",
                  value: 182,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "Nov-2020",
                  value: 217,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "Dec-2020",
                  value: 184,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "Jan-2021",
                  value: 191,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "Feb-2021",
                  value: 127,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
              ],
              insight: null,
              isDecimal: null,
            },
          ],
        },
      },
      {
        statusInfo: {
          statusCode: 200,
          statusMessage: "success",
          errorMessage: "",
        },
        responseData: {
          chartType: "polararea",
          visualizationCode: "diversity",
          chartFormat: null,
          drillDownChartId: "none",
          filterKeys: null,
          customData: null,
          dates: null,
          filter: null,
          data: [
            {
              headerName: "Diversity",
              headerValue: 1228,
              headerSymbol: "number",
              colorPaletteCode: null,
              colorPaletteId: null,
              plots: [
                {
                  label: "Header",
                  name: "Male",
                  value: 843,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "Female",
                  value: 383,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
              ],
              insight: null,
              isDecimal: null,
            },
          ],
        },
      },
      {
        statusInfo: {
          statusCode: 200,
          statusMessage: "success",
          errorMessage: "",
        },
        responseData: {
          chartType: "bar",
          visualizationCode: "numberOfPositions",
          chartFormat: null,
          drillDownChartId: "none",
          filterKeys: null,
          customData: null,
          dates: null,
          filter: null,
          data: [
            {
              headerName: "MDO's",
              headerValue: 431720.3772538068,
              headerSymbol: "number",
              colorPaletteCode: null,
              colorPaletteId: null,
              plots: [
                {
                  label: "Header",
                  name: "ISTM",
                  value: 320,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "ISRO",
                  value: 267,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "NIC",
                  value: 250,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "DRDO",
                  value: 250,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "LBSNA",
                  value: 200,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "AYUSH",
                  value: 180,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "UIDAI",
                  value: 156,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "DoPT",
                  value: 150,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "SVPNPA",
                  value: 143,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "NIRDPR",
                  value: 121,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
              ],
              insight: null,
              isDecimal: null,
            },
          ],
        },
      },
      {
        statusInfo: {
          statusCode: 200,
          statusMessage: "success",
          errorMessage: "",
        },
        responseData: {
          chartType: "bar",
          visualizationCode: "cbpOnBroadingTrend",
          chartFormat: null,
          drillDownChartId: "none",
          filterKeys: null,
          customData: null,
          dates: null,
          filter: null,
          data: [
            {
              headerName: "ISTM",
              headerValue: null,
              headerSymbol: null,
              colorPaletteCode: null,
              colorPaletteId: null,
              plots: [
                {
                  label: "header",
                  name: "Jan",
                  value: 21,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "Feb",
                  value: 25,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "Mar",
                  value: 30,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "Apr",
                  value: 35,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "May",
                  value: 42,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "Jun",
                  value: 47,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "Jul",
                  value: 50,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "Aug",
                  value: 75,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "Sep",
                  value: 82,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "Oct",
                  value: 120,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "Nov",
                  value: 128,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "Dec",
                  value: 130,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
              ],
              insight: null,
              isDecimal: null,
            },
            {
              headerName: "Harrappa",
              headerValue: null,
              headerSymbol: null,
              colorPaletteCode: null,
              colorPaletteId: null,
              plots: [
                {
                  label: "header",
                  name: "Jan",
                  value: 15,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "Feb",
                  value: 22,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "Mar",
                  value: 34,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "Apr",
                  value: 42,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "May",
                  value: 60,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "Jun",
                  value: 73,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "Jul",
                  value: 80,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "Aug",
                  value: 97,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "Sep",
                  value: 109,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "Oct",
                  value: 130,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "Nov",
                  value: 144,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "Dec",
                  value: 151,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
              ],
              insight: null,
              isDecimal: null,
            },
            {
              headerName: "JPAL",
              headerValue: null,
              headerSymbol: null,
              colorPaletteCode: null,
              colorPaletteId: null,
              plots: [
                {
                  label: "header",
                  name: "Jan",
                  value: 10,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "Feb",
                  value: 18,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "Mar",
                  value: 25,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "Apr",
                  value: 38,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "May",
                  value: 43,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "Jun",
                  value: 58,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "Jul",
                  value: 69,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "Aug",
                  value: 80,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "Sep",
                  value: 94,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "Oct",
                  value: 110,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "Nov",
                  value: 121,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "Dec",
                  value: 135,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
              ],
              insight: null,
              isDecimal: null,
            },
            {
              headerName: "Udemy",
              headerValue: null,
              headerSymbol: null,
              colorPaletteCode: null,
              colorPaletteId: null,
              plots: [
                {
                  label: "header",
                  name: "Jan",
                  value: 40,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "Feb",
                  value: 65,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "Mar",
                  value: 70,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "Apr",
                  value: 92,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "May",
                  value: 108,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "Jun",
                  value: 113,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "Jul",
                  value: 147,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "Aug",
                  value: 160,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "Sep",
                  value: 185,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "Oct",
                  value: 209,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "Nov",
                  value: 230,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "Dec",
                  value: 253,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
              ],
              insight: null,
              isDecimal: null,
            },

            {
              headerName: "ISB",
              headerValue: null,
              headerSymbol: null,
              colorPaletteCode: null,
              colorPaletteId: null,
              plots: [
                {
                  label: "header",
                  name: "Jan",
                  value: 25,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "Feb",
                  value: 30,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "Mar",
                  value: 43,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "Apr",
                  value: 57,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "May",
                  value: 66,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "Jun",
                  value: 79,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "Jul",
                  value: 91,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "Aug",
                  value: 113,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "Sep",
                  value: 128,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "Oct",
                  value: 144,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "Nov",
                  value: 160,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "Dec",
                  value: 175,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
              ],
              insight: null,
              isDecimal: null,
            },
          ],
        },
      },
      {
        statusInfo: {
          statusCode: 200,
          statusMessage: "success",
          errorMessage: "",
        },
        responseData: {
          chartType: "",
          visualizationCode: "learningTrend",
          chartFormat: null,
          drillDownChartId: "none",
          filterKeys: null,
          customData: null,
          dates: null,
          filter: null,
          data: [
            {
              headerName: "Learning Time",
              headerValue: 431720.3772538068,
              headerSymbol: "number",
              colorPaletteCode: null,
              colorPaletteId: null,
              plots: [
                {
                  label: "Header",
                  name: "Apr-2020",
                  value: 631.8648329412255,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "May-2020",
                  value: 295.25799994127203,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "Jun-2020",
                  value: 1658.7826694690932,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "Jul-2020",
                  value: 64810.795044640516,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "Aug-2020",
                  value: 94765.17582970156,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "Sep-2020",
                  value: 62954.23232729481,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "Oct-2020",
                  value: 27367.78634477248,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "Nov-2020",
                  value: 67071.49751383436,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "Dec-2020",
                  value: 36885.41300287151,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "Jan-2021",
                  value: 44833.261666659295,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "Feb-2021",
                  value: 30446.310021680656,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
              ],
              insight: null,
              isDecimal: null,
            },
            {
              headerName: "User Average",
              headerValue: 2414.6296621315787,
              headerSymbol: "number",
              colorPaletteCode: null,
              colorPaletteId: null,
              plots: [
                {
                  label: "Header",
                  name: "Apr-2020",
                  value: 21.06216109804085,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "May-2020",
                  value: 9.524451611008775,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "Jun-2020",
                  value: 36.861837099313185,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "Jul-2020",
                  value: 535.6264053276076,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "Aug-2020",
                  value: 357.60443709321345,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "Sep-2020",
                  value: 319.56463110301934,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "Oct-2020",
                  value: 150.37245244380483,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "Nov-2020",
                  value: 309.0852419992367,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "Dec-2020",
                  value: 200.46420110256255,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "Jan-2021",
                  value: 234.72911867360887,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "Header",
                  name: "Feb-2021",
                  value: 239.73472458016263,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
              ],
              insight: null,
              isDecimal: null,
            },
          ],
        },
      },
      {
        statusInfo: {
          statusCode: 200,
          statusMessage: "success",
          errorMessage: "",
        },
        responseData: {
          chartType: "horizontal_bar",
          visualizationCode: "noOfCompetenciesByMdo",
          chartFormat: null,
          drillDownChartId: "none",
          filterKeys: null,
          customData: null,
          dates: null,
          filter: null,
          data: [
            {
              headerName: "Number of competencies",
              headerValue: null,
              headerSymbol: null,
              colorPaletteCode: null,
              colorPaletteId: null,
              plots: [
                {
                  label: "header",
                  name: "DRDO",
                  value: 98,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "NIC",
                  value: 87,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "AYUSH",
                  value: 78,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "ISRO",
                  value: 67,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "ISTM",
                  value: 48,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "LBSNA",
                  value: 32,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "NIRDPR",
                  value: 18,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "UIDAI",
                  value: 12,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "SVPNPA",
                  value: 9,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "DoPT",
                  value: 4,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
              ],
              insight: null,
              isDecimal: null,
            },
          ],
        },
      },
    ],
    widgetData: [
      {
        statusInfo: {
          statusCode: 200,
          statusMessage: "success",
          errorMessage: "",
        },
        responseData: {
          chartType: "metric",
          visualizationCode: "competenciesCount",
          chartFormat: null,
          drillDownChartId: "none",
          filterKeys: null,
          customData: null,
          dates: null,
          filter: null,
          data: [
            {
              headerName: "Competencies",
              headerValue: 98,
              headerSymbol: "number",
              colorPaletteCode: null,
              colorPaletteId: null,
              plots: [],
              insight: null,
              isDecimal: false,
            },
          ],
        },
      },
      {
        statusInfo: {
          statusCode: 200,
          statusMessage: "success",
          errorMessage: "",
        },
        responseData: {
          chartType: "metric",
          visualizationCode: "approvedWorkAllocations",
          chartFormat: null,
          drillDownChartId: "none",
          filterKeys: null,
          customData: null,
          dates: null,
          filter: null,
          data: [
            {
              headerName: "Work allocations",
              headerValue: 2430,
              headerSymbol: "number",
              colorPaletteCode: null,
              colorPaletteId: null,
              plots: [],
              insight: null,
              isDecimal: false,
            },
          ],
        },
      },
    ],
  };

  dashboardTwo = {
    showFilters: "true",
    showWidgets: "false",
    filtersDetails: [
      {
        name: "Content",
        id: 1,
        key: "content",
        values: [
          "All",
          "MDO's",
        ],
      },
    ],
    visualizationDetails: [
      {
        row: 1,
        name: "Visualization Row 1",
        vizArray: [
          {
            id: 11,
            name: "Users Created Trend",
            dimensions: {
              height: 250,
              width: 6,
            },
            vizType: "chart",
            noUnit: true,
            isCollapsible: false,
            charts: [
              {
                id: "usersCreatedTrend",
                name: "Users Created Trend",
                code: "",
                chartType: "bar",
                filter: "",
                headers: [],
              },
            ],
          },
          {
            id: 11,
            name: "Courses Trend",
            dimensions: {
              height: 250,
              width: 6,
            },
            vizType: "chart",
            noUnit: true,
            isCollapsible: false,
            charts: [
              {
                id: "coursesTrend",
                name: "Courses Trend",
                code: "",
                chartType: "stackedbar",
                filter: "",
                headers: [],
              },
            ],
          },
        ],
      },
      {
        row: 1,
        name: "Visualization Row 2",
        vizArray: [
          {
            id: 11,
            name: "Users In Department",
            dimensions: {
              height: 250,
              width: 6,
            },
            vizType: "chart",
            noUnit: true,
            isCollapsible: false,
            charts: [
              {
                id: "usersInDepartment",
                name: "Users In Department",
                code: "",
                chartType: "pie",
                filter: "",
                headers: [],
              },
            ],
          },
        ],
      },
    ],
    chartDetails: [
      {
        statusInfo: {
          statusCode: 200,
          statusMessage: "success",
          errorMessage: "",
        },
        responseData: {
          chartType: "bar",
          visualizationCode: "usersCreatedTrend",
          chartFormat: null,
          drillDownChartId: "none",
          filterKeys: null,
          customData: null,
          dates: null,
          filter: null,
          data: [
            {
              headerName: "Users Created",
              headerValue: null,
              headerSymbol: null,
              colorPaletteCode: null,
              colorPaletteId: null,
              plots: [
                {
                  label: "header",
                  name: "May - 2021",
                  value: 13,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
              ],
              insight: null,
              isDecimal: null,
            },
          ],
        },
      },
      {
        statusInfo: {
          statusCode: 200,
          statusMessage: "success",
          errorMessage: "",
        },
        responseData: {
          chartType: "stackedbar",
          visualizationCode: "coursesTrend",
          chartFormat: null,
          drillDownChartId: "none",
          filterKeys: null,
          customData: null,
          dates: null,
          filter: null,
          data: [
            {
              headerName: "Draft",
              headerValue: null,
              headerSymbol: "number",
              colorPaletteCode: null,
              colorPaletteId: null,
              plots: [
                {
                  label: "header",
                  name: "May - 2021",
                  value: 4324,
                  valueLabel: "Value",
                  symbol: null,
                  parentName: null,
                  parentLabel: null,
                },
              ],
              insight: null,
              isDecimal: null,
            },
            {
              headerName: "Live",
              headerValue: null,
              headerSymbol: "number",
              colorPaletteCode: null,
              colorPaletteId: null,
              plots: [
                {
                  label: "header",
                  name: "May - 2021",
                  value: 3902,
                  valueLabel: "Value",
                  symbol: null,
                  parentName: null,
                  parentLabel: null,
                },
              ],
              insight: null,
              isDecimal: null,
            },
            {
              headerName: "Review",
              headerValue: null,
              headerSymbol: "number",
              colorPaletteCode: null,
              colorPaletteId: null,
              plots: [
                {
                  label: "header",
                  name: "May - 2021",
                  value: 1434,
                  valueLabel: "Value",
                  symbol: null,
                  parentName: null,
                  parentLabel: null,
                },
              ],
              insight: null,
              isDecimal: null,
            },
            {
              headerName: "Processing",
              headerValue: null,
              headerSymbol: "number",
              colorPaletteCode: null,
              colorPaletteId: null,
              plots: [
                {
                  label: "header",
                  name: "May - 2021",
                  value: 3904,
                  valueLabel: "Value",
                  symbol: null,
                  parentName: null,
                  parentLabel: null,
                },
              ],
              insight: null,
              isDecimal: null,
            },
          ],
        },
      },
      {
        statusInfo: {
          statusCode: 200,
          statusMessage: "success",
          errorMessage: "",
        },
        responseData: {
          chartType: "bar",
          visualizationCode: "departmentTrend",
          chartFormat: null,
          drillDownChartId: "none",
          filterKeys: null,
          customData: null,
          dates: null,
          filter: null,
          data: [
            {
              headerName: "Departments",
              headerValue: null,
              headerSymbol: null,
              colorPaletteCode: null,
              colorPaletteId: null,
              plots: [
                {
                  label: "header",
                  name: "Apr - 2021",
                  value: 5,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
              ],
              insight: null,
              isDecimal: null,
            },
          ],
        },
      },
      {
        statusInfo: {
          statusCode: 200,
          statusMessage: "success",
          errorMessage: "",
        },
        responseData: {
          chartType: "pie",
          visualizationCode: "usersInDepartment",
          chartFormat: null,
          drillDownChartId: "none",
          filterKeys: null,
          customData: null,
          dates: null,
          filter: null,
          data: [
            {
              headerName: "Department",
              headerValue: null,
              headerSymbol: null,
              colorPaletteCode: null,
              colorPaletteId: null,
              plots: [
                {
                  label: "header",
                  name: "01307938306521497658",
                  value: 0,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "0131397178949058560",
                  value: 19067,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "0132245461338112000",
                  value: 716,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "0132394904236113920",
                  value: 1,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "KarthikTestCBP",
                  value: 520,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "ORG_001",
                  value: 126,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "igot",
                  value: 6,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "in.ekstep",
                  value: 330,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
                {
                  label: "header",
                  name: "in.sunbird",
                  value: 0,
                  valueLabel: "Value",
                  symbol: "number",
                  parentName: null,
                  parentLabel: null,
                },
              ],
              insight: null,
              isDecimal: null,
            },
          ],
        },
      },
    ],
  };


  ngOnInit() {
    if (this.selectedDashboardId === "") {
      this.selectedDashboardId = this.dashboardList[0].responseData[0].id
      this.currentDashboard.push(this.dashboardOne)
    }
  }

  getDashboardId(value: string) {
    this.selectedDashboardId = value

    if (this.selectedDashboardId == "overview") {
      this.currentDashboard = []
      this.currentDashboard.push(this.dashboardOne)
    }

    if (this.selectedDashboardId == "informatics") {
      this.currentDashboard = []
      this.currentDashboard.push(this.dashboardTwo)
    }
  }

  backToHome() {
    this.router.navigate(['page', 'home'])
  }

}
